#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  fortune -a
  print
fi

# Activate RBENV
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Blink red on errors
function error_blink() {
    blink1-tool --rgb 0xff,0,00 --blink 3 --millis=50 --delay=50 > /dev/null
}

trap error_blink HUP QUIT FPE KILL ALRM TERM

# Setting for the new UTF-8 terminal support in Lion
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#
# Aliases
#
alias git="hub"
alias gc="git commit -m"
alias ga="git add"
alias gs="git status"
alias gd="git diff"
alias gl='git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"'
alias cls="cd;clear"
alias c='pygmentize -O style=monokai -f console256 -g'
alias hideprev='history -d $((HISTCMD-2)) && history -d $((HISTCMD-1))' # Hide the previous command you just ran
alias yt='youtube-dl --write-description --write-info-json -o "/Volumes/Airy 3To/youtube-archive/%(uploader)s/%(stitle)s.%(ext)s"'
alias t="todo.sh"
alias ri='ri -f ansi'